/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Inquiry: typeof import('./src/components/MyDialog/inquiry.vue')['default']
    MyActionSheet: typeof import('./src/components/MyActionSheet/index.vue')['default']
    MyCell: typeof import('./src/components/common/MyCell/index.vue')['default']
    Mycontrol: typeof import('./src/components/common/Mycontrol/index.vue')['default']
    MyDatePicker: typeof import('./src/components/MyDatePicker/index.vue')['default']
    MyDatePickerCell: typeof import('./src/components/MyComponents/MyDatePickerCell.vue')['default']
    MyDialog: typeof import('./src/components/MyDialog/index.vue')['default']
    MyNumPickerCell: typeof import('./src/components/MyComponents/MyNumPickerCell.vue')['default']
    MyPicker: typeof import('./src/components/MyPicker/index.vue')['default']
    MyPickerCell: typeof import('./src/components/MyComponents/MyPickerCell.vue')['default']
    MySwitch: typeof import('./src/components/MySwitch/index.vue')['default']
    MyUpload: typeof import('./src/components/MyComponents/MyUpload.vue')['default']
    MyUploadzj: typeof import('./src/components/MyComponents/MyUploadzj.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutInputNumber: typeof import('@nutui/nutui-taro')['InputNumber']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutPagination: typeof import('@nutui/nutui-taro')['Pagination']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTable: typeof import('@nutui/nutui-taro')['Table']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
    SegmentedControl: typeof import('./src/components/SegmentedControl/index.vue')['default']
    TimeRangePicker: typeof import('./src/components/TimeRangePicker/index.vue')['default']
  }
}
