/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Inquiry: typeof import('./src/components/MyDialog/inquiry.vue')['default']
    MyActionSheet: typeof import('./src/components/MyActionSheet/index.vue')['default']
    MyCell: typeof import('./src/components/common/MyCell/index.vue')['default']
    Mycontrol: typeof import('./src/components/common/Mycontrol/index.vue')['default']
    MyDatePicker: typeof import('./src/components/MyDatePicker/index.vue')['default']
    MyDatePickerCell: typeof import('./src/components/MyComponents/MyDatePickerCell.vue')['default']
    MyDialog: typeof import('./src/components/MyDialog/index.vue')['default']
    MyNumPickerCell: typeof import('./src/components/MyComponents/MyNumPickerCell.vue')['default']
    MyPicker: typeof import('./src/components/MyPicker/index.vue')['default']
    MyPickerCell: typeof import('./src/components/MyComponents/MyPickerCell.vue')['default']
    MySwitch: typeof import('./src/components/MySwitch/index.vue')['default']
    MyUpload: typeof import('./src/components/MyComponents/MyUpload.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    SegmentedControl: typeof import('./src/components/SegmentedControl/index.vue')['default']
    TimeRangePicker: typeof import('./src/components/TimeRangePicker/index.vue')['default']
  }
}
